/// scr_letterObj(x, y, letter);

var posX = argument0;
var posY = argument1;
var letter = argument2;

if(letter == "a") return instance_create(posX, posY, obj_a);
if(letter == "b") return instance_create(posX, posY, obj_b);
if(letter == "c") return instance_create(posX, posY, obj_c);
if(letter == "d") return instance_create(posX, posY, obj_d);
if(letter == "e") return instance_create(posX, posY, obj_e);
if(letter == "f") return instance_create(posX, posY, obj_f);
if(letter == "g") return instance_create(posX, posY, obj_g);
if(letter == "h") return instance_create(posX, posY, obj_h);
if(letter == "i") return instance_create(posX, posY, obj_i);
if(letter == "j") return instance_create(posX, posY, obj_j);
if(letter == "k") return instance_create(posX, posY, obj_k);
if(letter == "l") return instance_create(posX, posY, obj_l);
if(letter == "m") return instance_create(posX, posY, obj_m);
if(letter == "n") return instance_create(posX, posY, obj_n);
if(letter == "o") return instance_create(posX, posY, obj_o);
if(letter == "p") return instance_create(posX, posY, obj_p);
if(letter == "q") return instance_create(posX, posY, obj_q);
if(letter == "r") return instance_create(posX, posY, obj_r);
if(letter == "s") return instance_create(posX, posY, obj_s);
if(letter == "t") return instance_create(posX, posY, obj_t);
if(letter == "u") return instance_create(posX, posY, obj_u);
if(letter == "v") return instance_create(posX, posY, obj_v);
if(letter == "w") return instance_create(posX, posY, obj_w);
if(letter == "x") return instance_create(posX, posY, obj_x);
if(letter == "y") return instance_create(posX, posY, obj_y);
if(letter == "z") return instance_create(posX, posY, obj_z);
