/// scr_gen_drop(posX, letters);

var letter = argument1;
var posX = argument0;

if(letter == "a") return instance_create(posX, 100, obj_d_a);
if(letter == "b") return instance_create(posX, 100, obj_d_b);
if(letter == "c") return instance_create(posX, 100, obj_d_c);
if(letter == "d") return instance_create(posX, 100, obj_d_d);
if(letter == "e") return instance_create(posX, 100, obj_d_e);
if(letter == "f") return instance_create(posX, 100, obj_d_f);
if(letter == "g") return instance_create(posX, 100, obj_d_g);
if(letter == "h") return instance_create(posX, 100, obj_d_h);
if(letter == "i") return instance_create(posX, 100, obj_d_i);
if(letter == "j") return instance_create(posX, 100, obj_d_j);
if(letter == "k") return instance_create(posX, 100, obj_d_k);
if(letter == "l") return instance_create(posX, 100, obj_d_l);
if(letter == "m") return instance_create(posX, 100, obj_d_m);
if(letter == "n") return instance_create(posX, 100, obj_d_n);
if(letter == "o") return instance_create(posX, 100, obj_d_o);
if(letter == "p") return instance_create(posX, 100, obj_d_p);
if(letter == "q") return instance_create(posX, 100, obj_d_q);
if(letter == "r") return instance_create(posX, 100, obj_d_r);
if(letter == "s") return instance_create(posX, 100, obj_d_s);
if(letter == "t") return instance_create(posX, 100, obj_d_t);
if(letter == "u") return instance_create(posX, 100, obj_d_u);
if(letter == "v") return instance_create(posX, 100, obj_d_v);
if(letter == "w") return instance_create(posX, 100, obj_d_w);
if(letter == "x") return instance_create(posX, 100, obj_d_x);
if(letter == "y") return instance_create(posX, 100, obj_d_y);
if(letter == "z") return instance_create(posX, 100, obj_d_z);
